version: '3.7'

services:
  l4d4_host:
    build:
      context: .
    expose:
      - 3030
    restart: always
    volumes:
      - .:/app


# docker network create -d bridge evilcorp
networks:
  default:
    external: true
    name: evilcorp